### ISSUE TITLE
Detecting the amount of paged RAM is broken

### ISSUE THREAD

**Issue by mgkaiser** [irmen/cx16assem#2]
The ROM routine which detects the amount of paged RAM is broken in R41 emulator.  There will always be at least 512k of paged RAM.   So if the ROM routine reports zero paged RAM, assume 512k.

**Comment by irmen** [comment]
I don't understand what the issue is.
The amount of hiram is reported correctly, here is me running on official R41 + roms :
![image](https://user-images.githubusercontent.com/1771820/217077902-8d16cfff-3c0b-49a3-8177-8bd83bdb97fe.png)

**Comment by mgkaiser** [comment]
When I run cx16assem on the R41 emulator it tells me there are 0 pages of paged RAM available and it requires at least 10.   Cx16Shell mem command ALSO reports 0 paged RAM.  The underlying KERNAL routine that prog8 calls to detect that returns 0 as well.   The kernal routine is broken,  cx16assem is not usable on R41.

**Comment by irmen** [comment]
I cannot reproduce this behavior with the offical R41 emulator+rom.bin.
The kernal itself also reports the correct amount of paged ram in the boot message.

For reference here are the hashes of the rom.bin (extracted from the r41 emulator zip) that I'm using:
```
 /Downloads/x16emu_linux-r41 $ sha256sum rom.bin  
 04d64de7ccc2c608f38eaa87672e4f7f76a92540602de994e32ce02dc979483  rom.bin
 ~/Downloads/x16emu_linux-r41 $ md5sum rom.bin
 bed5e695af878dcc0e53d8e819f2066b  rom.bin
```

**Comment by mgkaiser** [comment]
If you set the emulator to 2048k extended RAM, the kernal reports ZERO extended RAM.  If you leave it at 512k it works.  No fix needed to assembler and low priority fix to Kernal since 512k is plenty.

**Comment by irmen** [comment]
Ah - I never used the increased RAM configuration before. But indeed, setting it at 2048 seems to trigger the issue. I wonder how the kernal itself still reports the correct amount in the boot message.

What is your proposal?  Work around the '0' response and assume 512 Kb in that case, even when there is infact more?

**Comment by mgkaiser** [comment]
I now propose it is not your problem.  There is an open issue on the Kernal and I will comment on that.  I think nobody’s fixed the kernal because the default configuration works.  At most maybe make a note in your README.  While we’re all working on an emulator it’s not too hard to just back down the amount of extended RAM.   If I finally lay hands on a real CX16, I will probably bump it up to 1024k, but code for 512k and use the upper 512k to install my “private stuff” out of the way of anything else the community writes.

**Comment by irmen** [comment]
Yeah I just discovered this https://github.com/commanderx16/x16-rom/pull/377 
I shall try to compile that PR branch to check if it indeed fixes the kernal issue.

**Comment by irmen** [comment]
It doesn't , but I can explain why -- MEMTOP returns the amount of hiram in 8 kb chunks.
2 Megabyte = 256 such chunks.   Which doesn't fit in the accumulator so you get 0 back.

**Comment by mgkaiser** [comment]
Checking every page is redundant.  I think the board only supports installing RAM in quanta of 512k.  You can have 0k, 512k, 1024k, 1536k or 2048k.   No other amounts are valid due to the board design.  So kernal should check if bank 1, 65, 129 and 193.  If bank 1 exists then there is at least 512k, bank 65 exists there is at least 1024k, bank 129 exists there is at least 1536k and bank 193 exists there is 2048k.  Also upon inspecting the prototype board, I think there is actually 512k of Low RAM with most of it inaccessible!    Look at the picture: https://hackaday.com/wp-content/uploads/2021/08/x16-prototype.jpg

**Comment by irmen** [comment]
well, it is what it is, MEMTOP is defined to return the number of 8Kb hiram chunks.

**Comment by irmen** [comment]
After a short discussion on discord we agreed that 0 means 256 = 2048 Kb of Hiram, as a Commander X16 machine with actual zero hiram won't exist as it cannot boot (kernal requires a bank for its variables).

So this is what I'll change in the routines in the assembler and the shell.
