### ISSUE TITLE
assembly stops after first .include

### ISSUE THREAD

**Issue by PaulForgey** [irmen/cx16assem#3]
cannot .include more than one file. This makes it impossible to, for instance, .include zero page definitions

**Comment by irmen** [comment]
yeah, that should work. Next time I have some time to spend on the assembler, I'll have a look.

**Comment by PaulForgey** [comment]
I've had about 30 minutes to grok p8 and what's going on in there, so I could be totally off base with this PR, but it does solve the issue for me.

**Comment by irmen** [comment]
your PR seems to indeed be a solution to the issue. Thanks!
